### ISSUE TITLE
ANSI X9.62 support

### ISSUE THREAD

**Issue by jeperipi** [J08nY/ecgen#1]
Thanks for sharing the tool and code. Anyway, I tried to generate the ANSI X9.62  but got error "Error generating a curve. state = 2"

This is the command that I used. ./ecgen --fp -p -r -s -u 192

Thanks again

**Comment by J08nY** [comment]
Right, I should have added a note somewhere that the ANSI X9.62 algo isn't yet implemented. Will do that now.

With the current workload I have I guess the soonest I could implement it  is around the end of June/beginning of July. Sorry for the inconvenience, ANSI X9.62 is a rather verbose spec so might take a bit of work, although the infrastructure is there. Will see, but I will try to get to it asap.

**Comment by J08nY** [comment]
The ANSI X9.62 generation procedure branch was just merged in 0d068cefe5f43d69fb7bae0c7882598c1213f60b. Will put up a new release soon.
