### ISSUE TITLE
Wrong CM discriminant computation.

### ISSUE THREAD

**Issue by vojtechsu** [J08nY/ecgen#12]
https://github.com/J08nY/ecgen/blob/5ed1f3f15acb12617dc7da25ec2642a0f70cbf12/src/gen/metadata.c#L28-L29

It seems that you compute CM disc as square-free part of trace^2-4*char. This is correct only up to multiplication of 4. See for example [safecurves](https://en.wikipedia.org/wiki/Fundamental_discriminant) or [wiki](https://en.wikipedia.org/wiki/Fundamental_discriminant)

**Comment by J08nY** [comment]
Could you suggest a fix? How could this be computed correctly? I can do the pari implementation, so just the pseudocode works.

**Comment by J08nY** [comment]
Fixed by 3e1aefd54ed04787d6ef8b8648b582e563554819.
