### ISSUE TITLE
Please upload ecgen.exe, for windows directly. I can't build it with Cmake, Make, or visual studio

### ISSUE THREAD

**Issue by softwarekamal** [J08nY/ecgen#14]
Please I need to test your beautiful library. But I got error messages. I try Clang compiler, VS 2022, I can't compile it.

Can you upload binary release directly so we can enjoy and test :(

![image](https://user-images.githubusercontent.com/33269552/168605264-b3da7008-8c4b-4791-a0f1-be6d7e1cc77c.png)

Please am wait your help

**Comment by J08nY** [comment]
I'm sorry, Windows is not supported and I will not be able to find the time to support it/figure out how to run ecgen there.
