### ISSUE TITLE
Golang elliptic.CurveParams compatibility

### ISSUE THREAD

**Issue by pedroalbanese** [J08nY/ecgen#16]
Greetings!

Could you tell me how to generate curves compatible with the Go language's elliptic.CurveParams library?

It happens that none of the generated parameters works for digital signature. How to proceed?

Thanks in advance.

**Comment by J08nY** [comment]
Well that really depends on the kind of checks that the library does. However, I would recommend to use standard parameters provided by the library (unless you are doing some testing/playing around).
