### ISSUE TITLE
Linking error on Arch Linux

### ISSUE THREAD

**Issue by maple3142** [J08nY/ecgen#17]
Compiling on Arch Linux using `make` gives error like this:

```
cc -I. -I../lib -DNDEBUG -O2 -DGIT_COMMIT=\"d523dd7\" -Wall -o ecgen ecgen.o cm/anomalous.o cm/cm_any.o cm/cm.o cm/cm_prime.o cm/p1363.o cm/supersingular.o exhaustive/ansi.o exhaustive/arg.o exhaustive/brainpool.o exhaustive/brainpool_rfc.o exhaustive/check.o exhaustive/exhaustive.o gen/curve.o gen/equation.o gen/field.o gen/gens.o gen/hex.o gen/metadata.o gen/order.o gen/point.o gen/seed.o invalid/invalid.o invalid/invalid_thread.o io/cli.o io/input.o io/output.o math/koblitz.o math/poly.o math/subgroup.o math/twists.o misc/config.o misc/types.o obj/curve.o obj/point.o obj/subgroup.o util/bits.o util/memory.o util/random.o util/str.o util/timeout.o -L../lib/parson -L../lib/sha1 -L../lib/pari  -lrt -lpari -lpthread -lparson -lsha1
/usr/bin/ld: gen/gens.o: in function `gens_get_embedding':
gens.c:(.text+0x885): undefined reference to `order'
/usr/bin/ld: gen/gens.o: in function `gens_check_embedding':
gens.c:(.text+0x933): undefined reference to `order'
collect2: error: ld returned 1 exit status
```

https://github.com/J08nY/ecgen/blob/d523dd7fcec48d411e43749cb1696af27771bc7e/src/gen/gens.c#L105-L107

Current pari/gp version on Arch Linux is `2.15.1-1`, so I tried to compiled it on Debian 11 too and it works. Maybe this comes some breaking changes from pari/gp, but I can't find the `order` function in the [documentation](https://pari.math.u-bordeaux.fr/pub/pari/manuals/2.13.0/libpari.pdf) of pari 2.13.0.

**Comment by J08nY** [comment]
Huh, I haven't touched this in a while so it will likely need a few touches here and there to keep it up with current libpari. Will have a look when I find some time.
