### ISSUE TITLE
Does this option work? --threads=NUM

### ISSUE THREAD

**Issue by alanthie** [J08nY/ecgen#19]
This option --threads=NUM does not fire multiple threads for me.
Is it a compile flag to enable?

Linux:
ecgen 0.7.6
Compiled with: GP/PARI CALCULATOR Version 2.15.2 (released)

Example:
./ecgen --fp -m 16g --threads=8 -v -k 1 -p  -r 1024 -o ../../../../egen_ec_curves/ec1024_2.txt

Thanks

**Comment by J08nY** [comment]
Hi.

I had a quick look and it seems I only parallelized the generation of invalid curves for a given curve. Thus the argument only applies to that specific case and is ignored otherwise. This is not ideal but I do not have the bandwidth to do anything about it. If you want to parallelize a computation like this I suggest just running multiple processes in parallel and gathering the results manually. This should properly parallelize and saturate the CPU, of course then you need to have enough memory for all the processes but they should not require much (if I remember correctly, random curve search has  a quite small footprint).

**Comment by alanthie** [comment]
Hi Jan,

Thanks for having taken the time to answer.

I would look at the code when I have time.
Pari/GP is a big piece of code to undesrtand and very abstract!
I saw that your code call the elliptic curve functions of Pari/GP.
I dont know if the ellxyz() functions have been optimized for multithread speedup when generating a single ec curve.

The hard part is the computation of the order of the ec curve to verify it is a prime number ("sea" algorithm).
I did not find any good implementation of "sea" in C++ (using GMP) on the web!

I'm developing a cryptocraphy tool and generating EC curve is very time consuming.
[Alternatively, I may auto generate new ec private/public keys (very fast) on a given big EC curve  everytime messages are exchange, in order to maintain the "perfect secrety (one time pad)" goal of my tool.]
https://github.com/alanthie/Encryptions

Still trying to get a 2048+ bits ec curve!

Thanks again for the info.
AL

________________________________

**Comment by J08nY** [comment]
> I dont know if the ellxyz() functions have been optimized for multithread speedup when generating a single ec curve.

They likely do not, and even if they did, this `--threads` option is not passed to them, so it has no effect.

> The hard part is the computation of the order of the ec curve to verify it is a prime number ("sea" algorithm). I did not find any good implementation of "sea" in C++ (using GMP) on the web!

Pari/GP implements point counting via the SEA algorithm and ecgen uses this. You however need the seadata
PARI data package> https://pari.math.u-bordeaux.fr/packages.html#packages
If you receive this error you are missing it: `seadata not found, this will probably take quite some time.`

> I'm developing a cryptocraphy tool and generating EC curve is very time consuming. [Alternatively, I may auto generate new ec private/public keys (very fast) on a given big EC curve everytime messages are exchange, in order to maintain the "perfect secrety (one time pad)" goal of my tool.] https://github.com/alanthie/Encryptions

I see. I do not recommend generating custom curves for cryptography, even though they are prime order and you can verify some properties, you are better off relying on a standard curve. Similarly, rolling your own crypto, with however many layers and however complicated, is usually not a good idea.
