### ISSUE TITLE
Speed up generating a curve with given order

### ISSUE THREAD

**Issue by JOHNKRAM** [J08nY/ecgen#23]
For generating a curve with a given composite `order`, factorizing the `order` and calling the `addprimes` function with all prime factors of the order during the initialization phase can greatly speed up the calculation of `bnfisintnorm`.

**Comment by J08nY** [comment]
This is actually done already (somewhat) if you specify the order as a comma-separated list of factors. See in file `cm.c`:

https://github.com/J08nY/ecgen/blob/master/src/cm/cm.c#L170C11-L170C11

If the order is specified as one number it is not factored, as in some cases that would be infeasible (think RSA-modulus-like orders with large bitsizes, or actually anything large and not smooth). I do not think adding this factoring step is worth it. To force it, just specify the order as a list of factors (that is the fastest), or if you want the factoring to be done automatically, specify an additional factor of 1 (e.g. `ecgen --fp -n 220458815440483907578809551792550246427,1 128`).

I will add better documentation of this.
