### ISSUE TITLE
Please support building hyperelliptic curves covers !

### ISSUE THREAD

**Issue by ytrezq** [J08nY/ecgen#29]
For any binary curve, the aim is to map the discrete logarithm to an hyperelliptic curve. It’s something as much well known as pairings. See https://hal.science/hal-01121942/document for details.

**Comment by J08nY** [comment]
This tool is not focused on such curves, only ordinary/supersingular prime and binary extension field curves.
You can email the authors of the paper to ask for their code.

**Comment by ytrezq** [comment]
A French researcher replying to a non researcher email address asking his code. Sorry to br chatty but tou have to learn about the country.
