### ISSUE TITLE
Please support generating twisted curves that come from twisted fields.

### ISSUE THREAD

**Issue by ytrezq** [J08nY/ecgen#30]
A typicall example is BN curves where their sextic extension are defined over $\mathbb{F}_p^2 = \mathbb{F}_p[x]/(x^2+1)$. So an option to specify the underlying finite field in deeper details need to be provided.

**Comment by J08nY** [comment]
I do not understand this request. There is now an option for generating BN curves. They are prime-field curves. If you want to do more with them import them into Sage for example and play with them there.

**Comment by J08nY** [comment]
I see. Well for this the same argument as for the hyperelliptic stuff applies, I do not really want to go to extension fields with ecgen as that would seriously overcomplicate the implementation. I think this kind of post-processing of curves is better suited to be done in Sagemath anyway. So I suggest you import the curve there and compute these things manually.

**Comment by ytrezq** [comment]
@J08nY except I use tools because I don’t know how to do it manually.

**Comment by J08nY** [comment]
Then I think the better approach is to ask on something like stackoverflow on how to do this specific thing in Sagemath (or other computational algebra tool of your choice) or perhaps ask Sagemath developers if this is a thing that could be added. I do not see it as a core feature that should be implemented in ecgen.

**Comment by ytrezq** [comment]
@J08nY such question are unswered for months.
