### ISSUE TITLE
undefined reference to "polisirreducible"

### ISSUE THREAD

**Issue by ZetaTwo** [J08nY/ecgen#8]
OS: Ubuntu 20.04.1 LTS

steps to reproduce:
```
apt install lib libpari-dev
git clone https://github.com/J08nY/ecgen.git
cd ecgen
make
```

result:
```
...
gen/field.c: In function ‘field_gen_input’:
gen/field.c:88:9: warning: implicit declaration of function ‘polisirreducible’; did you mean ‘isirreducible’? [-Wimplicit-function-declaration]
   88 |    if (!polisirreducible(poly)) {
      |         ^~~~~~~~~~~~~~
      |         isirreducible
...
field.c:(.text+0x6d7): undefined reference to `polisirreducible'
collect2: error: ld returned 1 exit status
```

changing to `isirreducible` seems to work but I don't know if that is the correct function to use.

**Comment by J08nY** [comment]
Oh yeah, thanks for the reminder. Pari removed and changes some functions around and ecgen wasn't updated in the meantime to keep up. Your fix with `isirreducible` should work though.

**Comment by J08nY** [comment]
Ah okay, so Ubuntu 20.04. has pari version _2.11.2_ according to this listing: https://packages.ubuntu.com/focal/libpari-dev. And `isirreducible` was only renamed to `polisirreducible` in _2.12.1_ which is about 4 months old and I have no idea when it lands in Ubuntu. I will create a versioned macro in the meantime.

**Comment by ZetaTwo** [comment]
Nice! Thanks for the quick fix. A very minor thing, won't that define break if you hit PARI_VERSION_MAJOR=3 and PARI_VERSION_MINOR=0 ?

**Comment by J08nY** [comment]
Oh yeah, you are right, got my logic mixed up. Should be fixed now, thanks.

**Comment by ZetaTwo** [comment]
Awesome. Thanks again!

**Comment by noloader** [comment]
It looks like the change/rename should be guarded with `PARI_VERSION`. From PARI/GP 2.13, which now experiences a link error:

```
$ grep -IR _VERSION ~/ok2delete/include/pari/
/home/test/ok2delete/include/pari/paricfg.h:#define PARI_VERSION_CODE 134400
/home/test/ok2delete/include/pari/paricfg.h:#define PARI_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))
...
```

Maybe something like:

```c
#if PARI_VERSION_CODE >= PARI_VERSION(2,12,1)
    /* use polisirreducible  */
#else
    /* use isirreducible  */
#endif
```

**Comment by J08nY** [comment]
This is actually done in https://github.com/J08nY/ecgen/blob/master/src/misc/compat.h so I am unsure whats going on, maybe my logic is messed up. Will have a look.
