### ISSUE TITLE
Link error using PARI/GP 2.13.0

### ISSUE THREAD

**Issue by noloader** [J08nY/ecgen#9]
I'm building the latest `ecgen` tarball against PARI/GP 2.13.0. PARI/GP 2.13.0 was released in January 2021.

The build for `ecgen` is failing during link with:

```bash
/usr/bin/ld: invalid/invalid.o: in function `invalid_do':
invalid.c:(.text+0x68f): undefined reference to `pari_thread_sync'
/usr/bin/ld: gen/field.o: in function `field_gen_input':
field.c:(.text+0x673): undefined reference to `isirreducible'
collect2: error: ld returned 1 exit status
```

The first sign of trouble was:

```bash
invalid/invalid.c: In function 'invalid_curves_threaded':
invalid/invalid.c:242:2: warning: implicit declaration of function 'pari_thread_sync';
did you mean 'pari_thread_start'? [-Wimplicit-function-declaration]
  242 |  pari_thread_sync();
      |  ^~~~~~~~~~~~~~~~
      |  pari_thread_start
```

and

```bash
gen/field.c: In function 'field_gen_input':
gen/field.c:87:9: warning: implicit declaration of function 'isirreducible';
did you mean 'polisirreducible'? [-Wimplicit-function-declaration]
   87 |    if (!isirreducible(poly)) {
      |         ^~~~~~~~~~~~~
      |         polisirreducible
```

Here is the [Developer Guide](https://pari.math.u-bordeaux.fr/pub/pari/manuals/2.13.0/develop.pdf) for PARI/GP 2.13.0. Searching the manual does not show the functions.

Additionally, searching headers for the functions return no relevant hits:

```bash
$ grep -IR pari_thread_sync ~/ok2delete/include
$

$ grep -IR isirreducible ~/ok2delete/include
/home/test/ok2delete/include/pari/paridecl.h:long    polisirreducible(GEN x);
$
```
I'm guessing the PARI/GP API has changed a bit.

**Comment by J08nY** [comment]
This is quite weird. I am able to build ecgen with PARI 2.13.0 just fine. Indeed if you look at `src/gen/field.c` you see that there is a `polisirreducible` call there. There is also a define guard in `src/misc/compat.h` which defines `polisirreducible` to `isirreducible` if the PARI version  is < `2.12.1` which made the change from `isirreducible` to `polisirreducible`. I think this guard is somehow misbehaving in your environment.

One easy way to build and use ecgen with source versions of pari is to build it and then copy over the build files into `lib/pari` in the ecgen directory.

Something like this:
```shell
git clone https://github.com/J08nY/ecgen
cd ecgen
mkdir lib/pari
git submodule update --init
git clone https://pari.math.u-bordeaux.fr/git/pari.git
cd pari
./Configure
make all
cd src/headers
cp *.h ../../../lib/pari
cd ../..
cd Olinux-x86_64
cp libpari* ../../lib/pari
cp *.h ../../lib/pari
cd ../..
make
```
works for me.

Then you just need `LD_LIBRARY_PATH` pointing to the `lib/pari` directory.

**Comment by noloader** [comment]
Thanks @J08nY,

I guess the difference is, you're using Git and I am using the release tarball at https://github.com/J08nY/ecgen/archive/refs/tags/0.7.3.tar.gz.

**Comment by J08nY** [comment]
Ah, I seeeee. I need to push a new release because these fixes are not in it, apparently I forgot to do that.

**Comment by noloader** [comment]
@J08nY,

If you build an RC, I am happy to test it for you.

My build steps are fairly simple:

* `configure` (if present)
* `make` (with my site flags)
* `make {check|test}` (with my site flags)
* `sudo make install`

Thanks for the help.

**Comment by J08nY** [comment]
There is now a release that should fix these issues: https://github.com/J08nY/ecgen/releases/tag/0.7.4
